version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    reviewers:
      - matthewdeaves

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    reviewers:
      - matthewdeaves

  - package-ecosystem: docker
    directory: /config/traefik
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - matthewdeaves

  - package-ecosystem: docker
    directory: /config/apps/cookie
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - matthewdeaves
